# Generated by Django 5.2.7 on 2025-10-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
